### ISSUE TITLE
Accessing controller's velocity

### ISSUE THREAD

**Issue by Kaibaer** [TomorrowTodayLabs/NewtonVR#113]
I want to access the velocity of the Hands (Controllers) when they enter a collider. Therefore I have the following code:

public class WindowTrigger_MakeStatic : MonoBehaviour {

    public int counterOnHammering = 0;
    public string SpeedofController = "";

    void OnTriggerEnter (Collider other)
    {
        NVRHand Hand = other.GetComponent<NVRHand>();
        counterOnHammering += 1;

        //SpeedofController = Hand.GetVelocityEstimation().ToString();

        Debug.Log("NVR Collider noticed entering - Numbers of entering: " + counterOnHammering + " Speed of Controller: " + SpeedofController);
    }
}

The problem is the "SpeedofController" line. It does throw me a NullReferenceException, **when** the controllers are entering the collider box, which uses this script class. Not on start (what my guess was, that it awaits an NVRHand Object from start on).

But when I exclude this and just want to let me show the numbers of enterings, it does work. So my question is: How do I access the initialized RightHand's/LeftHand's velocity on entering the collider? As this question seems to be very basic, I also want to mention, that I am fairly new to the Unity environment.

**Comment by SmartCarrion** [comment]
I'm guessing you have more than one trigger collider entering and not all of them have a 'NVRHand' above them!  So then the GetComponent is returning null.  Make sure you have your layers set right, so that only the one collider you want to test is being checked.  Or put a tag on it, and do an 'if' for that tag.

Also, it matters whether you are in physical hand mode or transparent hand mode, they are separate game objects at runtime.  Pause the game and check your hierarchy.  Maybe you are capturing a trigger on the wrong hand.  Debug.log what is hitting OnTriggerEnter and what is 'Hand'

**Comment by keithbradner** [comment]
Going to assume this is fixed
