### ISSUE TITLE
Teleportation whilst holding an object

### ISSUE THREAD

**Issue by mimminito** [TomorrowTodayLabs/NewtonVR#13]
It seems that teleporting whilst holding an object is broken. If you pick up an object and then teleport the object will disappear from your hand, and be left where you teleported from.

**Comment by keithbradner** [comment]
Good catch! We'll get that fixed.

**Comment by starsoccer** [comment]
I think I missed how exactly to enable/setup teleporting with Newton VR?

**Comment by bcoyle** [comment]
@starsoccer, drop the NVR Example Teleporter (script) onto each hand. My only suggestion with the teleporter would be having a toggle switch to choose between mid-trigger, full to teleport vs. full trigger, then release to teleport. Otherwise I thoroughly enjoy using the grip buttons for interactions. Although most new folks don't even realize those buttons are there.

**Comment by keithbradner** [comment]
We fixed this :)
