### ISSUE TITLE
NVRInteractibleItem follow latency 

### ISSUE THREAD

**Issue by AndersMalmgren** [TomorrowTodayLabs/NewtonVR#16]
Hi guys, excellent work on the library, We are using it for our Multiplayer shooter.
I have tried to modify the FixedUpdate to get it to follow more quickly but no luck, have you have any progress in this matter?

**Comment by thestonefox** [comment]
Hey, the way I solved better 1:1 tracking on grabbed objects is to use a fixed joint on the controller to the object instead of updating its position via update.

This works well for tracking, but it's not without its draw backs as it's creates other issues in collision physics (which I solve by just breaking the joint if the collisions go crazy)

**Comment by AndersMalmgren** [comment]
Cool, will have to look into that, you dont have a branch of NewtonVR you wanna share? :D

**Comment by thestonefox** [comment]
No sorry. I have my own toolkit, but I think Newton vr does some things in a cool way so I'm using it for inspiration

**Comment by AndersMalmgren** [comment]
InteractGrab from the SteamVR toolkit can be a good starting point if you guys want to go down the joint path

https://github.com/thestonefox/SteamVR_Unity_Toolkit/blob/master/Assets/SteamVR_Unity_Toolkit/Scripts/SteamVR_InteractGrab.cs

**Comment by keithbradner** [comment]
Fixed :D
