### ISSUE TITLE
Updated SteamVR 2.0.1 compatibility

### ISSUE THREAD

**Issue by Oyshoboy** [TomorrowTodayLabs/NewtonVR#191]
Hello! 
Is the updated SteamVR 2.0.1 compatibility planned?

Thank you :)

**Comment by SmartCarrion** [comment]
Looks like this plugin is abandoned, right?  The best bet is probably to stick with steamvr v1, or I might go through the work to rip out Newton and just use VRTK.  I'm just not sure if I can get the same game feel that I worked on for so long!

**Comment by SmartCarrion** [comment]
TomorrowTodayLabs is listed as 'permanently closed' on google if that means anything

**Comment by keithbradner** [comment]
Unfortunately vrtk isn't really compatible with SteamVR Input yet either. Yeah, I'd list this as abandonded unless somebody has a super good reason it should be updated. I've added the core of NewtonVR (moving objects using velocities) into the SteamVR Unity Plugin itself. Just use throwables and set the attachment flag to Velocity Movement. There's examples on the left throwables table. 

![image](https://user-images.githubusercontent.com/198704/51699458-a641f380-1fc1-11e9-9793-4846a66762ea.png)

**Comment by Oyshoboy** [comment]
@zite Thanks for answer! I'm really loving your solution & physics!

**Comment by joostbos** [comment]
@zite can you point us to a simple example or documentation for this? The pdf in the SteamVR plugin has very little information about the Interaction System.

It works fine in the Interaction Example, but that has a lot of extra stuff that I don't need in my own application. I don't need hovering functionality, I don't need fancy hands, I don't need snap turns. But I can not delete them because they are all part of the player prefab and Unity won't allow deleting stuff from an instance of a prefab. And without documentation, I am worried that I delete stuff that I actually do need.

Also my tennis racket should alway be atached to a controller (or tracker), without having to press the trigger to pick it up. How can I achieve that?

Thanks.

**Comment by keithbradner** [comment]
Sorry, I don't check this project much anymore. There's steamvr unity plugin docs here: https://valvesoftware.github.io/steamvr_unity_plugin/
