### ISSUE TITLE
Using multiple scripts together?

### ISSUE THREAD

**Issue by dre4mer12345** [TomorrowTodayLabs/NewtonVR#33]
Hi there,

I'm trying to create a handle that can pull out, and have rotational control. I can use the scripts to make either one work alone, but I can' figure out how I can get both functions out of a handle. 

Any ideas? Thank you!

**Comment by naabel** [comment]
Since NVR relies on physics to control items, a lot depends on how you construct the scene objects. In this case, I found I could make a handle as you describe with a configurable joint and rigidbody. I constructed a primitive handle with nested cylinders, and attached a Rigidbody and Configurable Joint to the root parent. I limited motion and rotation to the Y axis on the joint, and used a modified NVRLever on the handle object with all the lever specific stuff taken out. The script uses position on y from start position to determine if the handle is pulled out. When the handle is not pulled out, the Rigidbody constraints only allow movement on the Y, if the handle is pulled out, the Rigidbody constraints only allow rotation on the Y.
