### ISSUE TITLE
Push button

### ISSUE THREAD

**Issue by smygarn** [TomorrowTodayLabs/NewtonVR#35]
I rotated the push button to be put on a wall instead of a table. It didn't really workout since I think the speed towards the initial position is depending on world postion y or something like that?

**Comment by rustinlee** [comment]
The button in the example is done using position constraints on the Rigidbody, which are in worldspace. I've had success managing button position with a Configurable Joint with xyz rotation locked/x and z movement locked with y movement limited, a very low linear limit and a high spring force. This results in something similar to a spring joint but with local space constraints instead of world space. Use code similar to NVR Button to trigger a button press when the button moves too far. This approach works no matter what angle the button is at.

**Comment by rustinlee** [comment]
Actually, I lasted tested NVR's buttons on what is now a several weeks old version of the repo, @zite in #28 seems to imply that this might not be the case any more.

**Comment by keithbradner** [comment]
Yeah, we're using local constraints now. Should work find on a wall

**Comment by naabel** [comment]
Closing, see commit https://github.com/TomorrowTodayLabs/NewtonVR/commit/33351dafa940780e4f5c9ea3e49be3defec0a44e
