### ISSUE TITLE
Event driven design

### ISSUE THREAD

**Issue by smygarn** [TomorrowTodayLabs/NewtonVR#39]
Event driven design should be implemented to all controls.

For example in a slider:

```
    public delegate void ResultAction(string tag, float value);
    public event ResultAction OnResultChanged;
    float previousValue;

 if (previousValue != CurrentValue)
        {
            previousValue = CurrentValue;
            if (OnResultChanged != null)
            {
                OnResultChanged(tag, CurrentValue);
            }
          }
```

**Comment by keithbradner** [comment]
I think we probably will implement this soon. Going to look at using UnityEvents instead though, they seem pretty nice.

**Comment by smygarn** [comment]
Great. Looking forward to upcoming updates. Do you have any plans of a slack channel to be able to expand the community around this?

**Comment by omgwtfgames** [comment]
I started implementing some events like this for item attachment/detachment too (eg https://github.com/omgwtfgames/NewtonVR/compare/e4bf5edcfac128dd60e848a63e3c4a84c6a533a1...feature/onattach-events ).

It's not yet cleaned up as a proper pull request though since I haven't done things consistently - I started by using plain old delegate events on AttachJoint but then used UnityEvents on InteractableItem. I think UnityEvents is probably the better option since the Inspector integration can be useful and I don't see any significant disadvantages.

Some discussion about how we should implement this consistently across the library would be good.

**Comment by flarb** [comment]
Yeah this is 100% needed. I had a bunch of this setup for my old hand control library that I'd like to move over to this.

**Comment by rpgwhitelock** [comment]
Another nod for this. I use UnityEvents heavily in my own script framework - they are incredibly useful! Can hook up simple behaviours in the inspector without compiling. Very convenient when adding general polish and effects too.

**Comment by MarkwarNickA** [comment]
Closed, see Trello card (https://trello.com/c/OI53wkQo)

**Comment by naabel** [comment]
Closed, see Trello card (https://trello.com/c/OI53wkQo)
