### ISSUE TITLE
Interacting with objects with two hands.

### ISSUE THREAD

**Issue by hcorion** [TomorrowTodayLabs/NewtonVR#47]
Hi, we've been demoing a VR game we made over a course of 4 weeks and we have a steering wheel that is an NVRInteractableRotater (I think) and I got a lot of requests (from our team as well) to have the ability to grab the steering wheel with two hands and drive. Is this possible with NewtonVR as it currently stands? Would this be something the devs could implement?

**Comment by SmartCarrion** [comment]
I see this human behavior frequently in demos too.  My game has boxes that people have to pick up, and they just want to do it with two hands because that makes more sense to them.  I should probably put a handle that makes it look like something you grab with one hand, but I've also been thinking about how to implement two handed grabbing.  

Other people, like Anton Hand, have been solving this VR problem for guns, using the grip with a second hand to apply a smoothing algorithm to motion of the gun so it is easier to look down the scope.  Seems like we could do something similar with Newton, just make the NVRInteractableItem 'RotationDelta' and 'PositionDelta' track to a smoothed transform that is halfway between the two hands instead of 'in' one hand.  There are a few weird cases to deal with of course.

**Comment by naabel** [comment]
Closing, future feature, see Trello card (https://trello.com/c/B0axSuZ6)
