### ISSUE TITLE
NewtonVR does not handle Despawned/Destroyed NVRitems cleanly

### ISSUE THREAD

**Issue by SmartCarrion** [TomorrowTodayLabs/NewtonVR#49]
In my game items you are holding, or could interact with, may explode (i.e. despawn).  If I don't handle this specially, the item can stick around in 'CurrentlyHoveringOver' and you still grab onto it if you push the grab button after it is despawned.  This totally screws with the controller behavior and frustrates users, as you are grabbing nothing and the controller just seems broken.

One fix i've done is to call 'ForceDetach' if something you are holding despawns.  That seems to fix one case, but not the 'hovering over something' case.  I'm working on finding another way to remove that item cleanly from both hands, hopefully without checking both hands 'CurrentlyHoveringOver' for every despawned item.

**Comment by SmartCarrion** [comment]
I added ForceEndHovering to NVRHand and called that and ForceDetach whenever something despawns.  See code below:

```
        public virtual void ForceEndHovering(NVRInteractable interactable)
        {
            if (CurrentlyHoveringOver.ContainsKey(interactable) == true)
            {              
                        CurrentlyHoveringOver.Remove(interactable);
            }
        }
```

I don't know how to tun this into a pull request, sorry

**Comment by naabel** [comment]
Looks like it was fixed in https://github.com/TomorrowTodayLabs/NewtonVR/commit/fe1085b77058b0ada709fabd1f141e7c3eee52f5. It's based off using Gameobject.Destroy() to destroy the object, the deregistering happens then. If you simple need the Interactable to be deregistered, use Interactable.Deregister(<what you want deregistered>).

If you're disabling the objects, I'd create a inheriting class of NVRInteractable that has similar functionality in OnDisable().
