### ISSUE TITLE
UI Clicks won't work with inherited implementation of NVRHand

### ISSUE THREAD

**Issue by scatterlogical** [TomorrowTodayLabs/NewtonVR#67]
I wanted to inherit the NVRHand class to include some new features (initially interactable object highlighting) but found that after inheriting the class and replacing the NVRHand scripts on the controllers with it, I am unable to click on elements in world-space canvases. I removed my code from the class, and found that even an empty class definition still breaks the UI clicks, so this should be easily reproducible by creating a new script with the contents
`namespace NewtonVR
{
    public class NVRHandExtended : NVRHand
    {}
}`
apply that to a controller on the rig, and disable the original NVRHand script.

**Comment by naabel** [comment]
Hi Scatterlogical,

When you say World-Space Canvases, you mean the floating GUI in the example scene? The one behind the door?

With NewtonVR Ver 0.94, I created a class NVRHandExtended : NVRHand, and if I removed the original NVRHand component from the Left/Right hand gameobjects and replaced it with NVRHandExtended, I was able to use the GUI normally.

Did you make sure to re-reference the Left/Right hand gameobjects in the NVRPlayer Left/Right hand fields? It could be that because the fields are of type NVRHand, they're retaining the reference to the disabled scripts. Try removing the vanilla NVRHand scripts entirely.

**Comment by SmartCarrion** [comment]
I've implemented object highlighting and dual handed interactions, it feels
crazy that we are all repeating each other's work. Any way we can share
this stuff better?

As a side note, I could really use a good object highlighting shader, my
solutions so far have looked crappy on most objects. let me know if you
found something good!

**Comment by keithbradner** [comment]
Thanks for reporting this. I'm not seeing this if I set LeftHand and RightHand on the player. This may have been fixed in 0.9. Let me know if you're still having this issue.
