### ISSUE TITLE
Teleporting with Object Broken on 1.14

### ISSUE THREAD

**Issue by gsurla** [TomorrowTodayLabs/NewtonVR#98]
Teleporting while holding an object is broken on v1.14.  When teleporting, the NVRInteractableItem the player is holding will drop straight down instead of teleporting with the player.  

I'm currently using Vive Teleport, Newton VR on Unity 5.5f3

**Comment by SmartCarrion** [comment]
It is likely detaching due to distance.  So I don't think it is actually
purposefully dropping the object, you are just moving the hand away so fast
that you are breaking the connection.

The solution I found is when i teleport the player I calculate how far that
would move the held object, then manually add that to the object transform.
i.e. you have to teleport the object too.

So this is less of bug report, more of a feature request for a built-in transport object function.  One workaround would be to parent the object to NVRPlayer (not NVRHand) when it is held, but that could break other systems people build, even if it reparented to the original object when dropped (e.g. imagine if the original object had been deactivated)

**Comment by gsurla** [comment]
I'll try teleporting the actual object instead.  Thanks.  I'll close this issue since, as you pointed out, it turns out to be more of a feature request than a bug.
